[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.5.2",
    "lightgbm>=4.6.0",
    "pandas>=2.3.3",
    "scikit-learn==1.6.1",
    "shap>=0.48.0",
]
